import = ["/home/klliio/.config/alacritty/catppuccin.toml"]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 14

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 4
y = 2
